import type { DashboardState } from "@/domain/types";

const now = new Date().toISOString();

const defaultLlm: DashboardState["llm"] = {
  mode: "mock",
  effectiveMode: "mock",
  requestedMode: "mock",
  simulationForced: false,
  autonomyEnabled: true,
  openaiConfigured: false,
  models: { worker: "mock", supervisor: "mock" },
  tokensUsedThisTick: 0,
  tokenBudgetPerTick: 25_000,
};

export const mockSeed: DashboardState = {
  generatedAt: now,
  agents: [
    {
      id: "leonardo",
      name: "Leonardo",
      role: "coordinator",
      status: "working",
      currentTaskId: "task-001",
      avatarSeed: "blue-katana-visor",
      deskLabel: "Coordination Desk",
      online: true,
      lastHeartbeatAt: now,
      lastSuccessfulTaskId: null,
      lastSuccessfulTaskAt: null,
    },
    {
      id: "raphael",
      name: "Raphael",
      role: "urgent_executor",
      status: "idle",
      currentTaskId: null,
      avatarSeed: "red-sai-armor",
      deskLabel: "Rapid Response Desk",
      online: true,
      lastHeartbeatAt: now,
      lastSuccessfulTaskId: null,
      lastSuccessfulTaskAt: null,
    },
    {
      id: "donatello",
      name: "Donatello",
      role: "technical_specialist",
      status: "working",
      currentTaskId: "task-002",
      avatarSeed: "purple-tech-bo",
      deskLabel: "Systems Desk",
      online: true,
      lastHeartbeatAt: now,
      lastSuccessfulTaskId: null,
      lastSuccessfulTaskAt: null,
    },
    {
      id: "michelangelo",
      name: "Michelangelo",
      role: "creative_specialist",
      status: "working",
      currentTaskId: "task-003",
      avatarSeed: "orange-nunchaku-art",
      deskLabel: "Creative Desk",
      online: true,
      lastHeartbeatAt: now,
      lastSuccessfulTaskId: null,
      lastSuccessfulTaskAt: null,
    },
    {
      id: "splinter",
      name: "Splinter",
      role: "supervisor",
      status: "working",
      currentTaskId: null,
      avatarSeed: "master-mentor",
      deskLabel: "Supervisor Console",
      online: true,
      lastHeartbeatAt: now,
      lastSuccessfulTaskId: null,
      lastSuccessfulTaskAt: null,
    },
  ],
  tasks: [
    {
      id: "task-001",
      title: "Coordinate nighttime recon run",
      description: "Confirm telemetry windows and coordinate synchronized updates.",
      priority: "high",
      status: "in_progress",
      assignedTo: "leonardo",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "task-002",
      title: "Patch message parser",
      description: "Investigate edge-case payload parsing and deploy guarded fix.",
      priority: "critical",
      status: "in_progress",
      assignedTo: "donatello",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "task-003",
      title: "Draft operator mission brief",
      description: "Write concise brief for Telegram mission updates and handoff.",
      priority: "medium",
      status: "assigned",
      assignedTo: "michelangelo",
      createdAt: now,
      updatedAt: now,
    },
  ],
  logs: [
    {
      id: "log-001",
      agentId: "leonardo",
      level: "info",
      message: "Mission coordination heartbeat nominal.",
      source: "system",
      createdAt: now,
    },
    {
      id: "log-002",
      agentId: "donatello",
      level: "warn",
      message: "Parser fallback path triggered; active mitigation in progress.",
      output: "fallback_mode=true; sample_count=3",
      source: "openclaw",
      createdAt: now,
    },
    {
      id: "log-003",
      agentId: "splinter",
      level: "info",
      message: "Supervisor cycle completed, 3 active assignments monitored.",
      source: "supervisor",
      createdAt: now,
    },
  ],
  agentMessages: [],
  llm: defaultLlm,
  agentLLM: {
    leonardo: { provider: "mock" },
    raphael: { provider: "mock" },
    donatello: { provider: "mock" },
    michelangelo: { provider: "mock" },
    splinter: { provider: "mock" },
  },
};

